### ISSUE TITLE
Enumeration of joystick directions

### ISSUE THREAD

**Issue by StephaneBranly** [SurrogateInc/surrortg-sdk#2]
The enumeration of the joystick directions is not the same between the library and the site admin interface.
`{UP, LEFT, RIGHT, DOWN}` on the website respectively associated with `{BOTTOM, LEFT, RIGHT, TOP}` in the library

[code-reference](https://github.com/SurrogateInc/surrortg-sdk/blob/1e122a5362bc25a65b21f69c09f1ed01b2b53f42/surrortg/inputs/joystick.py#L11-L19)

**Comment by ollipal** [comment]
Thanks for the report! I was able to reproduce the issue. Hopefully we get this fixed for the next release.

**Comment by ollipal** [comment]
UP and DOWN are now displayed correctly on the website.
